name: Unit Testing
on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - master
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
      - run: echo "Semua Berjalan dengan Sempurna"
      - run: echo "Selamat Mengerjakan tugas teman - teman Semua"
      - run: echo "Nothing to Lose"


  unit-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - run: go test ./...

  unit-testing-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - run: go test -v -cover ./...